name: Build (Unsigned)

on:
  push:
    branches:
      - 'main'
  release:
    types: [released]
  pull_request:
    types:
      - 'ready_for_review'
      - 'opened'
      - 'synchronize'
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm install --include=dev

      - name: Download uv
        run: npm run download linux

      - name: Build
        run: npm run dist

      - name: Publish artifact - GUI - UNSIGNED
        uses: actions/upload-artifact@v4
        with:
          name: 'Invoke Community Edition.AppImage - UNSIGNED'
          path: 'dist/Invoke Community Edition.AppImage'

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm install --include=dev

      - name: Download uv
        run: npm run download mac

      - name: Build
        run: npm run dist

      - name: Publish artifact - GUI - UNSIGNED
        uses: actions/upload-artifact@v4
        with:
          name: 'Invoke Community Edition.dmg - UNSIGNED'
          path: 'dist/Invoke Community Edition.dmg'

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm install --include=dev

      - name: Download uv
        run: npm run download win

      - name: Build
        run: npm run dist

      - name: Publish artifact - GUI - UNSIGNED
        uses: actions/upload-artifact@v4
        with:
          name: 'Invoke Community Edition.exe - UNSIGNED'
          path: 'dist/Invoke Community Edition.exe'
